using System.ComponentModel.DataAnnotations;

namespace AppShared.ViewModels.Users
{
    public class RegisterAccountViewModel
    {
        #region Properties

        /// <summary>
        ///     Email which is used for account registration.
        /// </summary>
        [Required]
        public string Email { get; set; }

        /// <summary>
        ///     Password of account.
        /// </summary>
        [Required]
        public string Password { get; set; }

        /// <summary>
        ///     Nickname of account owner.
        /// </summary>
        [Required]
        public string Nickname { get; set; }

        /// <summary>
        ///     Client capcha code which is generated by Google re-captcha service.
        /// </summary>
        [Required]
        public string CaptchaCode { get; set; }

        #endregion
    }
}