language: node_js
node_js:
- 9.8.0

# Caching phrase.
cache:
    directories:
        - node_modules
        
# Installation preparation phrase.
before_install:
- cd 'A - SOURCE CODE\\B - CLIENT\\A - WEB\\B - USER'

# Dependency installation phrase.
install:
- npm install

# Build phrase
script:
- npm run build

