language: node_js
node_js:
- 9.8.0

# Variable declaration.
env:
    global:
        - CLIENT_DIRECTORY="A - SOURCE CODE/B - CLIENT/A - WEB/B - USER"

# Caching phrase.
cache:
    directories:
        - $CLIENT_DIRECTORY/node_modules
        
# Installation preparation phrase.
before_install:
- cd $CLIENT_DIRECTORY

# Dependency installation phrase.
install:
- npm install

# Build phrase
script:
- npm run build

