//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HttpMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.HttpMessages", typeof(HttpMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_ALREADY_DISABLED.
        /// </summary>
        public static string AccountAlreadyDisabled {
            get {
                return ResourceManager.GetString("AccountAlreadyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_IS_DISABLED.
        /// </summary>
        public static string AccountIsDisabled {
            get {
                return ResourceManager.GetString("AccountIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_IS_IN_USE.
        /// </summary>
        public static string AccountIsInUse {
            get {
                return ResourceManager.GetString("AccountIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_NOT_FOUND.
        /// </summary>
        public static string AccountIsNotFound {
            get {
                return ResourceManager.GetString("AccountIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_IS_PENDING.
        /// </summary>
        public static string AccountIsPending {
            get {
                return ResourceManager.GetString("AccountIsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIZATION_NOT_FOUND.
        /// </summary>
        public static string CategorizationNotFound {
            get {
                return ResourceManager.GetString("CategorizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY_NOT_FOUND.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENT_HAS_BEEN_REPORTED.
        /// </summary>
        public static string CommentHasBeenReported {
            get {
                return ResourceManager.GetString("CommentHasBeenReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENT_NOT_FOUND.
        /// </summary>
        public static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENT_REPORT_NOT_FOUND.
        /// </summary>
        public static string CommentReportNotFound {
            get {
                return ResourceManager.GetString("CommentReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FACEBOOK_CODE_IS_INVALID.
        /// </summary>
        public static string FacebookCodeIsInvalid {
            get {
                return ResourceManager.GetString("FacebookCodeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOGLE_CODE_IS_INVALID.
        /// </summary>
        public static string GoogleCodeIsInvalid {
            get {
                return ResourceManager.GetString("GoogleCodeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION_NOT_FOUND.
        /// </summary>
        public static string InformationNotFound {
            get {
                return ResourceManager.GetString("InformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST_CATEGORIZATION_NOT_FOUND.
        /// </summary>
        public static string PostCategorizationNotFound {
            get {
                return ResourceManager.GetString("PostCategorizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST_HAS_BEEN_CATEGORIZED.
        /// </summary>
        public static string PostHasBeenCategorized {
            get {
                return ResourceManager.GetString("PostHasBeenCategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST_HAS_BEEN_REPORTED.
        /// </summary>
        public static string PostHasBeenReported {
            get {
                return ResourceManager.GetString("PostHasBeenReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST_HASNT_BEEN_FOLLOWED_YET.
        /// </summary>
        public static string PostHasntBeenFollowedYet {
            get {
                return ResourceManager.GetString("PostHasntBeenFollowedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST_NOT_FOUND.
        /// </summary>
        public static string PostNotFound {
            get {
                return ResourceManager.GetString("PostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST_REPORT_NOT_FOUND.
        /// </summary>
        public static string PostReportNotFound {
            get {
                return ResourceManager.GetString("PostReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN_NOT_FOUND.
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_NOT_COMMENT_OWNER.
        /// </summary>
        public static string UserNotCommentOwner {
            get {
                return ResourceManager.GetString("UserNotCommentOwner", resourceCulture);
            }
        }
    }
}
