//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainShared.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppShared.Resources.NotificationMessages", typeof(NotificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_SOMEONE_COMMENTED_TOPIC.
        /// </summary>
        public static string SomeoneCommentedTopic {
            get {
                return ResourceManager.GetString("SomeoneCommentedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_SOMEONE_CREATED_CATEGORY.
        /// </summary>
        public static string SomeoneCreatedCategory {
            get {
                return ResourceManager.GetString("SomeoneCreatedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_SOMEONE_CREATED_CATEGORY_GROUP.
        /// </summary>
        public static string SomeoneCreatedCategoryGroup {
            get {
                return ResourceManager.GetString("SomeoneCreatedCategoryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_TOPIC_ADDED_IN_CATEGORY..
        /// </summary>
        public static string SomeoneCreatedTopic {
            get {
                return ResourceManager.GetString("SomeoneCreatedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_SOMEONE_EDITED_CATEGORY.
        /// </summary>
        public static string SomeoneEditedCategory {
            get {
                return ResourceManager.GetString("SomeoneEditedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_SOMEONE_EDITED_CATEGORY_GROUP.
        /// </summary>
        public static string SomeoneEditedCategoryGroup {
            get {
                return ResourceManager.GetString("SomeoneEditedCategoryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_SOMEONE_FOLLOWED_CATEGORY.
        /// </summary>
        public static string SomeoneFollowedCategory {
            get {
                return ResourceManager.GetString("SomeoneFollowedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_SOMEONE_FOLLOW_YOUR_TOPIC.
        /// </summary>
        public static string SomeoneFollowedYourTopic {
            get {
                return ResourceManager.GetString("SomeoneFollowedYourTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_SOMEONE_REPLIED_YOUR_TOPIC.
        /// </summary>
        public static string SomeoneRepliedYourTopic {
            get {
                return ResourceManager.GetString("SomeoneRepliedYourTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_SOMEONE_REPORTED_TOPIC.
        /// </summary>
        public static string SomeoneReportedTopic {
            get {
                return ResourceManager.GetString("SomeoneReportedTopic", resourceCulture);
            }
        }
    }
}
