using System.ComponentModel.DataAnnotations;

namespace AuthenticationMicroService.ViewModels.User
{
    public class LoginViewModel
    {
        #region Properties

        /// <summary>
        ///     Email which is used for account login.
        /// </summary>
        [Required]
        public string Email { get; set; }

        /// <summary>
        ///     Password of account.
        /// </summary>
        [Required]
        public string Password { get; set; }

        /// <summary>
        /// Client capcha code which is generated by Google re-captcha service.
        /// </summary>
        [Required]
        public string CaptchaCode { get; set; }

        #endregion
    }
}
